-- 资产台账表
-- 基表: sap_data.zfi0056_99991231

CREATE TABLE IF NOT EXISTS jst_flat.asset_ledger (
    anln1               VARCHAR(255)    COMMENT '资产',
    anln2               VARCHAR(255)    COMMENT '次级',
    txt50               VARCHAR(255)    COMMENT '资产描述',
    menge               DECIMAL(38,2)   COMMENT '数量',
    meins               VARCHAR(255)    COMMENT '单位',
    txk20               VARCHAR(255)    COMMENT '资产大类',
    bukrs               VARCHAR(255)    COMMENT '公司',
    cbukrs              VARCHAR(255)    COMMENT '公司代码（清洗后）',
    cbuktx              VARCHAR(255)    COMMENT '公司描述（清洗后）',
    aktiv               VARCHAR(255)     COMMENT '资本化日期',
    afabg               VARCHAR(255)     COMMENT '计算开始',
    kostl               VARCHAR(255)    COMMENT '成本中心',
    ktext               VARCHAR(255)    COMMENT '成本中心名称',
    ndjar               VARCHAR(255)    COMMENT '折旧年限',
    kansw_begin         DECIMAL(38,2)   COMMENT '原值-期初原值',
    anbtr_out           DECIMAL(38,2)   COMMENT '原值-本期增加-外购',
    anbtr_pro           DECIMAL(38,2)   COMMENT '原值-本期增加-在建工程转固',
    anbtr_add_resell    DECIMAL(38,2)   COMMENT '原值-本期增加-转买集团内部公司资产',
    anbtr_add_others    DECIMAL(38,2)   COMMENT '原值-本期增加-其他',
    anbtr_add_sum       DECIMAL(38,2)   COMMENT '原值-本期增加-合计',
    anbtr_scrap         DECIMAL(38,2)   COMMENT '原值-本期减少-报废',
    anbtr_reduce_resell DECIMAL(38,2)   COMMENT '原值-本期减少-转卖集团内部公司资产',
    anbtr_sell          DECIMAL(38,2)   COMMENT '原值-本期减少-出售',
    anbtr_reduce_others DECIMAL(38,2)   COMMENT '原值-本期减少-其他',
    anbtr_reduce_sum    DECIMAL(38,2)   COMMENT '原值-本期减少-合计',
    anbtr_end           DECIMAL(38,2)   COMMENT '原值-期末原值',
    knafa_begin         DECIMAL(38,2)   COMMENT '累计折旧-期初折旧',
    nafaz_normal        DECIMAL(38,2)   COMMENT '累计折旧-本期增加-正常折旧',
    hsl_add_others      DECIMAL(38,2)   COMMENT '累计折旧-本期增加-其他',
    hsl_add_resell      DECIMAL(38,2)   COMMENT '累计折旧-本期增加-转买集团内部公司资产',
    hsl_add_sum         DECIMAL(38,2)   COMMENT '累计折旧-本期增加-合计',
    hsl_reduce_normal   DECIMAL(38,2)   COMMENT '累计折旧-本期减少-正常折旧',
    hsl_scrap           DECIMAL(38,2)   COMMENT '累计折旧-本期减少-报废',
    hsl_reduce_resell   DECIMAL(38,2)   COMMENT '累计折旧-本期减少-转卖集团内部公司资产',
    hsl_reduce_others   DECIMAL(38,2)   COMMENT '累计折旧-本期减少-其他',
    hsl_reduce_sum      DECIMAL(38,2)   COMMENT '累计折旧-本期减少-合计',
    hsl_period          DECIMAL(38,2)   COMMENT '累计折旧-本期折旧',
    hsl_end             DECIMAL(38,2)   COMMENT '累计折旧-期末折旧',
    hsl_end_net         DECIMAL(38,2)   COMMENT '期末净值',
    anred               VARCHAR(255)    COMMENT '标题',
    dept_id             VARCHAR(255)    COMMENT '部门编码',
    dept_name           VARCHAR(255)    COMMENT '部门名称',
    gdlgrp              VARCHAR(255)    COMMENT '资产类型',
    gdlgrp_txt          VARCHAR(255)    COMMENT '资产类型描述',
    fkbtx               VARCHAR(255)    COMMENT '功能范围',
    stort               VARCHAR(255)    COMMENT '存放位置',
    raumn               VARCHAR(255)    COMMENT '保管人',
    sernr               VARCHAR(255)    COMMENT '序列号',
    add_date            VARCHAR(8)      COMMENT '增量日期'
) COMMENT='资产台账表';
