-- 采购入库大表
-- 基表: sap_data.zmm0018_zmm0018

CREATE TABLE IF NOT EXISTS jst_flat.purchase_receipt_cn (
    bukrs         VARCHAR(255)    COMMENT '公司',
    cbukrs        VARCHAR(255)    COMMENT '公司代码（清洗后）',
    cbuktx        VARCHAR(255)    COMMENT '公司描述（清洗后）',
    werks         VARCHAR(255)    COMMENT '工厂',
    prctr         VARCHAR(255)    COMMENT '利润',
    cprctr        VARCHAR(255)    COMMENT '利润中心（清洗后）',
    cprctx        VARCHAR(255)    COMMENT '利润中心描述（清洗后）',
    ernam         VARCHAR(255)    COMMENT '创建人',
    uname         VARCHAR(255)    COMMENT '创建人名称',
    aedat         DATE            COMMENT '创建日期',
    bsart         VARCHAR(255)    COMMENT '凭证类型',
    ekgrp         VARCHAR(255)    COMMENT '采购组',
    ebeln         VARCHAR(255)    COMMENT '采购凭证号',
    ebelp         VARCHAR(255)    COMMENT '采购凭证行项目',
    lifnr         VARCHAR(255)    COMMENT '供应商代码',
    name1         VARCHAR(255)    COMMENT '供应商名称',
    mwskz         VARCHAR(255)    COMMENT '税码',
    text1         VARCHAR(255)    COMMENT '税值',
    matnr         VARCHAR(255)    COMMENT '物料',
    txz01         VARCHAR(255)    COMMENT '物料描述',
    matkl         VARCHAR(255)    COMMENT '物料组',
    wgbez         VARCHAR(255)    COMMENT '物料组名称',
    menge_ekpo    DECIMAL(38,2)   COMMENT '采购订单数量',
    meins         VARCHAR(255)    COMMENT '采购订单单位',
    mseht         VARCHAR(255)    COMMENT '单位文本',
    netpr         DECIMAL(38,2)   COMMENT '净价',
    peinh         DECIMAL(38,2)   COMMENT '价格单位',
    netwr         DECIMAL(38,2)   COMMENT '订单净值',
    waers         VARCHAR(255)    COMMENT '币别',
    wkurs         DECIMAL(38,2)   COMMENT '订单汇率',
    menge_ekbe    DECIMAL(38,2)   COMMENT '入库数量 (订单单位)',
    bamng         DECIMAL(38,2)   COMMENT '入库数量 (基本单位)',
    menge_jhcb    DECIMAL(38,2)   COMMENT '交货成本数量',
    meins_jb      VARCHAR(255)    COMMENT '基本计量单位',
    kschl         VARCHAR(255)    COMMENT '条件类型',
    vtext         VARCHAR(255)    COMMENT '条件类型名称',
    wrbtr         DECIMAL(38,2)   COMMENT '入库币别净总金额',
    zwrbtr        DECIMAL(38,2)   COMMENT '入库币别含税总金额',
    zwrbtr2       DECIMAL(38,2)   COMMENT '集团币别入库净值',
    zwrbtr3       DECIMAL(38,2)   COMMENT '集团币别入库含税值',
    bwart         VARCHAR(255)    COMMENT '入库类型',
    belnr         VARCHAR(255)    COMMENT '入库物料凭证号',
    buzei         VARCHAR(255)    COMMENT '入库物料凭证行项目号',
    budat         DATE            COMMENT '入库日期',
    charg         VARCHAR(255)    COMMENT '入库批次号',
    lgort         VARCHAR(255)    COMMENT '入库库存地',
    bktxt         VARCHAR(255)    COMMENT '入库操作人',
    belnr_2       VARCHAR(255)    COMMENT '入库会计凭证',
    knttp         VARCHAR(255)    COMMENT '科目分类类别',
    ptext         VARCHAR(255)    COMMENT '项目类型描述',
    hkont         VARCHAR(255)    COMMENT '统驭科目',
    bednr         VARCHAR(255)    COMMENT '跟踪编号',
    eindt         DATE            COMMENT '交货日期',
    ctype         VARCHAR(255)    COMMENT '费用类型',
    zwlzxl        VARCHAR(255)    COMMENT '物料组小类1',
    zjgpl         VARCHAR(255)    COMMENT '价格披露分类',
    zhxcl         VARCHAR(255)    COMMENT '核心材料',
    zgj           VARCHAR(255)    COMMENT '进口国家',
    zlb           VARCHAR(255)    COMMENT '类别',
    unit_price_excl_tax  DECIMAL(38,6)   COMMENT '入库不含税单价',
    unit_price_incl_tax  DECIMAL(38,6)   COMMENT '入库含税单价',
    remark        VARCHAR(255)    COMMENT '备注字段',
    is_calculated VARCHAR(255)    COMMENT '是否参与计算',
    delivery_amt  VARCHAR(255)    COMMENT '交货不含税总金额-原',
    per_sap       VARCHAR(255)    COMMENT '每-SAP',
    kbetr         DECIMAL(38,2)   COMMENT '税率（百分比）',
    comp_head     VARCHAR(255)    COMMENT '控股方'
) COMMENT '采购入库大表（中国区）';
