-- 物料明细表
-- 基表: dwd_dcp.DWD_S4_ACDOCA, dwd_dcp.DWD_BM_ACDOCA
-- 筛选条件: DWD_BW_ZTBPC002_ACC.cractx LIKE '%物料消耗%'，且排除64开头科目号

CREATE TABLE IF NOT EXISTS jst_flat.MATERIAL_DETAIL (
    rbukrs      VARCHAR(255)    COMMENT '公司代码',
    cbukrs      VARCHAR(255)    COMMENT '公司代码（清洗后）',
    cbuktx      VARCHAR(255)    COMMENT '公司描述（清洗后）',
    belnr       VARCHAR(255)    COMMENT '会计凭证号码',
    blart       VARCHAR(255)    COMMENT '凭证类型',
    budat       VARCHAR(255)    COMMENT '过账日期',
    sgtxt       VARCHAR(255)    COMMENT '项目文本',
    racct       VARCHAR(255)    COMMENT '科目号',
    cracct      VARCHAR(255)    COMMENT '科目编号（科目表）',
    cractx      VARCHAR(255)    COMMENT '科目描述',
    prctr       VARCHAR(255)    COMMENT '利润中心',
    cprctr      VARCHAR(255)    COMMENT '利润中心（清洗后）',
    cprctx      VARCHAR(255)    COMMENT '利润中心描述（清洗后）',
    rfarea      VARCHAR(255)    COMMENT '功能范围',
    cfartx      VARCHAR(255)    COMMENT '功能范围描述',
    rcntr       VARCHAR(255)    COMMENT '成本中心',
    ktext       VARCHAR(255)    COMMENT '成本中心名称',
    anred       VARCHAR(255)    COMMENT '标题',
    dept_id     VARCHAR(255)    COMMENT '部门编码',
    dept_name   VARCHAR(255)    COMMENT '部门名称',
    matnr       VARCHAR(255)    COMMENT '物料编号',
    maktx       VARCHAR(255)    COMMENT '物料描述',
    matkl       VARCHAR(255)    COMMENT '物料组',
    wgbez       VARCHAR(255)    COMMENT '物料组描述',
    mtbez       VARCHAR(255)    COMMENT '物料类型描述',
    tsl         DECIMAL(23,2)   COMMENT '金额（余额交易货币）',
    rtcur       VARCHAR(255)    COMMENT '余额交易货币',
    wsl         DECIMAL(23,2)   COMMENT '以交易货币计的金额',
    rwcur       VARCHAR(255)    COMMENT '交易货币（本位币）',
    msl         DECIMAL(23,2)   COMMENT '数量',
    runit       VARCHAR(255)    COMMENT '单位',
    werks       VARCHAR(255)    COMMENT '工厂',
    ebeln       VARCHAR(255)    COMMENT '采购凭证编号',
    kdauf       VARCHAR(255)    COMMENT '销售订单数',
    aufnr       VARCHAR(255)    COMMENT '订单号',
    lifnr       VARCHAR(255)    COMMENT '供应商帐号',
    kunnr       VARCHAR(255)    COMMENT '客户编号',
    data_source VARCHAR(255)    COMMENT '数据来源'
) COMMENT '物料明细表';
