-- ============================================================
-- 质量损失报表
-- 目标表：jst_flat.quality_loss_report
-- 数据来源：dwd_dcp.dwd_ims_quality_loss_report
-- ============================================================

CREATE TABLE IF NOT EXISTS jst_flat.quality_loss_report (
    id                      BIGINT          COMMENT '主键',
    company_code            VARCHAR(255)    COMMENT '公司代码',
    cbukrs                  VARCHAR(255)    COMMENT '公司代码（清洗后）',
    cbuktx                  VARCHAR(255)    COMMENT '公司描述（清洗后）',
    post_date               VARCHAR(255)    COMMENT '过账日期',
    data_source_code        VARCHAR(255)    COMMENT '数据来源代码',
    data_source             VARCHAR(255)    COMMENT '数据来源',
    profit_center_code      VARCHAR(255)    COMMENT '利润中心代码',
    cprctr                  VARCHAR(255)    COMMENT '利润中心（清洗后）',
    cprctx                  VARCHAR(255)    COMMENT '利润中心描述（清洗后）',
    profit_center_desc      VARCHAR(255)    COMMENT '利润中心描述',
    profit_group_code       VARCHAR(255)    COMMENT '利润中心组代码',
    profit_group_desc       VARCHAR(255)    COMMENT '利润中心组描述',
    cost_center_code        VARCHAR(255)    COMMENT '成本中心代码',
    cost_center_desc        VARCHAR(255)    COMMENT '成本中心描述',
    quality_loss_code       VARCHAR(255)    COMMENT '质量损失代码',
    new_quality_loss_code   VARCHAR(255)    COMMENT '新质量损失代码',
    is_person_check         VARCHAR(255)    COMMENT '是否个人质量损失考核数据',
    pre_after_sale          VARCHAR(255)    COMMENT '售前售后',
    is_warranty             VARCHAR(255)    COMMENT '是否保修期范围内',
    loss_type_one           VARCHAR(255)    COMMENT '质量损失类别一',
    loss_type_two           VARCHAR(255)    COMMENT '质量损失类别二',
    direct_cost             DECIMAL(38,2)   COMMENT '直接费用',
    indirect_cost           DECIMAL(38,2)   COMMENT '间接费用',
    total_cost              DECIMAL(38,2)   COMMENT '费用合计',
    salvage_value           DECIMAL(38,2)   COMMENT '残值回收值',
    actual_loss             DECIMAL(38,2)   COMMENT '实际损失值',
    internal_order          VARCHAR(255)    COMMENT '内部订单',
    after_service_case_no   VARCHAR(255)    COMMENT '售后服务个案号',
    problem_desc            TEXT            COMMENT '问题描述长文本',
    quality_notice_no       VARCHAR(255)    COMMENT '质量通知单号',
    supplier_name           VARCHAR(255)    COMMENT '供应商名称',
    material_factory        VARCHAR(255)    COMMENT '物料工厂',
    batch_no                VARCHAR(255)    COMMENT '批号',
    finish_storage_time     VARCHAR(255)    COMMENT '完工入库时间',
    actual_delivery_date    VARCHAR(255)    COMMENT '实际发货日期',
    root_cause_big          VARCHAR(255)    COMMENT '根本原因-大类',
    root_cause_small        VARCHAR(255)    COMMENT '根本原因-小类',
    abnormal_part           VARCHAR(255)    COMMENT '异常信息（部件）',
    abnormal_performance    TEXT            COMMENT '异常信息（异常表现）',
    duty_dept_d4            VARCHAR(255)    COMMENT '责任部门（D4）',
    sale_order_no           VARCHAR(255)    COMMENT '销售订单号',
    customer_name           VARCHAR(255)    COMMENT '客户名称',
    purchase_order          VARCHAR(255)    COMMENT '采购订单',
    production_order_no     VARCHAR(255)    COMMENT '生产订单号',
    gl_voucher_no           VARCHAR(255)    COMMENT '总账凭证号',
    line_item               VARCHAR(255)    COMMENT '行项目',
    voucher_sale_order      VARCHAR(255)    COMMENT '凭证销售订单',
    voucher_sale_line       VARCHAR(255)    COMMENT '凭证销售订单行项目',
    material_voucher        VARCHAR(255)    COMMENT '物料凭证',
    material_no             VARCHAR(255)    COMMENT '物料号',
    material_desc           VARCHAR(255)    COMMENT '物料描述',
    material_group          VARCHAR(255)    COMMENT '物料组',
    material_batch          VARCHAR(255)    COMMENT '批次号',
    quantity                VARCHAR(255)    COMMENT '数量',
    account_code            VARCHAR(255)    COMMENT '科目代码',
    remark1                 VARCHAR(255)    COMMENT '产品线大类',
    remark2                 VARCHAR(255)    COMMENT '产品系列口径',
    remark3                 VARCHAR(255)    COMMENT '实际责任单位',
    remark4                 VARCHAR(255)    COMMENT '是否质量相关',
    remark5                 VARCHAR(255)    COMMENT '备注'
) COMMENT='质量损失报表';
