CREATE TABLE IF NOT EXISTS jst_flat.bill_received (
    orig_no               VARCHAR(255)   COMMENT '票据号码',
    bill_type             VARCHAR(255)   COMMENT '票据类型：银票、商票、第三方票据、债权凭证',
    bill_flag             VARCHAR(255)   COMMENT '流通介质：纸票、电票',
    bill_money            DECIMAL(15,2)  COMMENT '票据金额',
    start_date            DATETIME       COMMENT '出票日期',
    end_date              DATETIME       COMMENT '到期日期',
    acceptor              VARCHAR(255)   COMMENT '承兑人',
    new_stm_issuofppr_ind VARCHAR(255)   COMMENT '出票标志：0 老系统出票、1 新系统出票',
    blgrdbagcrcl_prmt_ind VARCHAR(255)   COMMENT '是否允许分包：是、否',
    sbbll_rng_strt_sn     VARCHAR(255)   COMMENT '子票区间开始序号',
    sbbll_rng_end_sn      VARCHAR(255)   COMMENT '子票区间结束序号',
    repeat_rec_sign       VARCHAR(255)   COMMENT '回头票标识：是、否',
    acc_id                VARCHAR(255)   COMMENT '票据流水表id',
    acc_vid               VARCHAR(255)   COMMENT '票据主表ID（流水）',
    acc_vvid              VARCHAR(255)   COMMENT '票据从表id（流水）',
    status                VARCHAR(255)   COMMENT '审批处理状态：已删除、打回、暂存、提交、审批中、已完成、已拆包',
    opt_status            VARCHAR(255)   COMMENT '操作状态',
    send_sign             VARCHAR(255)   COMMENT '是否发送指令标志：0 否、1 是',
    brief_id              VARCHAR(255)   COMMENT '业务类型',
    business_date         DATETIME       COMMENT '业务归属日期',
    vice_id               VARCHAR(255)   COMMENT '票据从表id',
    vice_vid              VARCHAR(255)   COMMENT '票据主表id',
    corp_id               VARCHAR(255)   COMMENT '持票单位',
    bank_acc              VARCHAR(255)   COMMENT '持票单位账号',
    bank_name             VARCHAR(255)   COMMENT '持票单位账户银行名称',
    cn_accrecords         VARCHAR(255)   COMMENT '前手',
    type                  VARCHAR(255)   COMMENT '类型：0 应付票据、1 应收票据',
    code                  VARCHAR(255)   COMMENT '公司代码',
    cbukrs                VARCHAR(255)   COMMENT '公司代码（清洗后）',
    cbuktx                VARCHAR(255)   COMMENT '公司描述（清洗后）',
    bank_level            VARCHAR(255)   COMMENT '银行信用等级',
    jinpan_bill_type      VARCHAR(255)   COMMENT '金盘票据类型',
    jinpan_bill_code      VARCHAR(255)   COMMENT '金盘票据代码'
) COMMENT='资金流水-汇票（已签收）';
