CREATE TABLE jst_flat.electricity_bill_summary (
  bukrs   VARCHAR(255) COMMENT '公司代码',
  cbukrs  VARCHAR(255) COMMENT '公司代码（清洗后）',
  cbuktx  VARCHAR(255) COMMENT '公司描述（清洗后）',
  gjahr   VARCHAR(255) COMMENT '会计年度',
  monat   VARCHAR(255) COMMENT '会计期间',
  name1   VARCHAR(255) COMMENT '公司名称',
  wrbtr   DECIMAL(23,2) COMMENT '外购电费（含税，元）',
  wrbtr1  DECIMAL(23,2) COMMENT '外购电费（不含税，元）',
  werks   DECIMAL(23,2) COMMENT '外购电量（kw/h）',
  wrbtr2  DECIMAL(23,2) COMMENT '外购电均价（不含税，元）',
  werks1  DECIMAL(23,2) COMMENT '光伏自发电总量（kw/h)',
  werks2  DECIMAL(23,2) COMMENT '光伏自发自用量(kw/h)',
  werks3  DECIMAL(23,2) COMMENT '光伏上网电量(kw/h)',
  wrbtr3  DECIMAL(23,2) COMMENT '光伏上网售电电费含税金额（元）',
  wrbtr4  DECIMAL(23,5) COMMENT '光伏上网售电电费不含税金额（元）',
  wrbtr5  DECIMAL(11,9) COMMENT '光伏上网售电均价（不含税，元）',
  werks5  DECIMAL(23,3) COMMENT '光伏上网补贴电量(kw/h)',
  srsq    VARCHAR(255) COMMENT '光伏上网补贴电费收入属期',
  wrbtr6  DECIMAL(23,2) COMMENT '光伏上网补贴电费收入含税金额（元）',
  wrbtr7  DECIMAL(23,2) COMMENT '光伏上网补贴电费收入不含税金额（元）',
  wrbtr8  DECIMAL(23,2) COMMENT '光伏上网售电补贴均价（不含税，元）',
  wrbtr9  DECIMAL(23,3) COMMENT '耗电量合计 (kw/h)',
  zjd VARCHAR(255) COMMENT '基地'
) comment='电费汇总表';
