-- ============================================================
-- 目标表: jst_flat.material_backlog (物料积压表)
-- 数据来源: sap_data.zrmm_jyyj_05_zmm38 (SAP 物料积压经营月结)
-- ============================================================
INSERT INTO jst_flat.material_backlog (
    spmon, mtart, mtbez, matkl, wgbez,
    ekgrp, eknam, beskz,
    matnr, maktx, meins,
    werks, lgort, charg,
    labst, stprs, labst1, stprs1,
    sc4, sc6, c4, c6,
    c4_zj, c6_zj, c4_js, c6_js,
    xqsl, c10, dc4, dc6, symbsl,
    jyyy, jysm, jyzrbh, jyzrbm, sybtext1,
    jyzrr, clfabm, zxqksm,
    clyj, clzrbm, sybtext2,
    clmbsl, wcqx, cdate, csdat,
    wcgz, nocl, mbbl, clmbje,
    cfdat, cftext, cfzx,
    vbeln, bstkd_e, bezei_dbc, bezei_ry,
    kunnr, name_kh,
    zdmj, ckcb, acc, acc_1,
    sfkf, txr
)
SELECT
    t.SPMON,
    t.C15,
    t.MTBEZ,
    t.C14,
    t.WGBEZ,
    t.EKGRP,
    t.EKNAM,
    t.BESKZ,
    t.MATNR,
    t.C2,
    t.C3,
    t.WERKS,
    t.LGORT,
    t.CHARG,
    t.LABST,
    t.STPRS,
    t.LABST1,
    t.STPRS1,
    t.SC4,
    t.SC6,
    t.C4,
    t.C6,
    t.C4_ZJ,
    t.C6_ZJ,
    t.C4_JS,
    t.C6_JS,
    t.XQSL,
    t.C10,
    t.DC4,
    t.DC6,
    t.SYMBSL,
    t.JYYY,
    t.JYSM,
    t.JYZRBH,
    t.JYZRBM,
    t.SYBTEXT1,
    t.JYZRR,
    t.CLFABM,
    t.ZXQKSM,
    t.CLYJ,
    t.CLZRBM,
    t.SYBTEXT2,
    t.CLMBSL,
    t.WCQX,
    t.CDATE,
    t.CSDAT,
    t.WCGZ,
    t.NOCL,
    t.MBBL,
    t.CLMBJE,
    t.CFDAT,
    t.CFTEXT,
    t.CFZX,
    t.VBELN,
    t.BSTKD_E,
    t.BEZEI_DBC,
    t.BEZEI_RY,
    t.KUNNR,
    t.NAME_KH,
    t.ZDMJ,
    t.CKCB,
    t.ACC,
    t.ACC_1,
    t.SFKF,
    t.TXR
FROM sap_data.zrmm_jyyj_05_zmm38 t;
